FIX: data dictionary for distribution grids
WISPO-POP/PowerPlots.jl pull request #75
Opened 2021-08-13 22:04 UTC by keatsig

This PR modifies data dictionary for unbalanced distribution grid cases (supports openDSS files parsed by PowerModelsDistribution.jl) to account for the three-phase parameters.

2021-08-16 15:26 UTC, noahrhodes requested changes
Just one comment on the code! it looks good overall.

Can you also add some tests?  You can add a small distribution system and run the powerplot with it to check that code is run.

2021-08-16 15:26 UTC, noahrhodes commented on src/plots/plot_processing.jl
> +        )
This does not copy the metadata of the grid, like the name, per unit etc.  I would make a deep-copy of the old network and replace these component dictionaries with empty ones
```julia
case_dist = deepcopy(case)
for comp_type in ["gen","branch","bus","switch","transformer"]
    case_dist[comp_type] = Dict{String,Any}()
end
```

2021-08-24 23:05 UTC, noahrhodes approved these changes

2021-11-02 19:17 UTC, noahrhodes commented
Is PMD required as a dependency? (are any PMD functions called by Power Plots?).  This can make a big difference in allowing parallel precompilation of PowerPlots and PMD when updating the packages.

2021-11-02 19:17 UTC, noahrhodes commented
TODO:

- [ ] Update Changelog
- [ ] Update documentation

2022-01-07 18:43 UTC, noahrhodes commented
@keatsig I updated the changelog.  I this ready to merge?

2022-01-10 06:34 UTC, keatsig commented
Yes, it is ready to merge.
________________________________
From: noahrhodes ***@***.***>
Sent: Friday, January 7, 2022 12:44 PM
To: WISPO-POP/PowerPlots.jl ***@***.***>
Cc: KSHITIJ I GIRIGOUDAR ***@***.***>; Mention ***@***.***>
Subject: Re: [WISPO-POP/PowerPlots.jl] FIX: data dictionary for distribution grids (#75)


@keatsig<https://github.com/keatsig> I updated the changelog. I this ready to merge?

—
Reply to this email directly, view it on GitHub<https://github.com/WISPO-POP/PowerPlots.jl/pull/75#issuecomment-1007647107>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AKHNRKSQF6W5UCPA5MBLQVDUU4X7BANCNFSM5CELL43A>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-11 16:59 UTC, noahrhodes approved these changes

2022-01-11 17:01 UTC, merged